apiVersion : apps/v1
kind : Deployment
metadata: 
  name: {{ .Release.Name }}-deployment
  labels:
    app : {{ .Release.Name }}-app
    env: test
    owner: AT
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.container.image }}
          command: ["python3", "./app.py"]
          ports:
            - containerPort: {{ .Values.container.containerPort }}

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscale-app
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: {{ .Release.Name }}-deployment-autoscaling
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80